### ISSUE TITLE
skos-testing-tool is not workig

### ISSUE THREAD

**Issue by mroszkowski** [sparna-git/skos-testing-tool#12]
Hello, I've been using skos-testing-tool with my students for small projects. I've discovered recently that this service is not working. I've tried to upload a small vocabulary but I get an empty page. The same happens when I try to use your example. Could you please take a look at this issue?
All the best
Marcin

**Comment by tfrancart** [comment]
Yes, I confirm there is something wrong.

**Comment by tfrancart** [comment]
OK so I don't know what is wrong but the problem comes from the rule identified with code "usr" in qSKOS (Undefined SKOS resources). *uncheck* this box and the validation will work:

![image](https://user-images.githubusercontent.com/2728945/217504982-11709cae-66ae-4891-8995-6581301f26aa.png)

**Comment by mroszkowski** [comment]
Thanks a lot! It works!

**Comment by mroszkowski** [comment]
Skos-testing has been down for a couple of days. Are you planning to restore it?
